### PR TITLE
added package.json to install it through npm

### PR DESCRIPTION
**Pull request by lgrignon**
zip.js cannot be installed using npm because there is no package.json

I created a basic one, it should do the trick. Is it ok for you?

Thanks.

### CODE REVIEW

**Comment by bhollis** [comment]
This would be great to get merged - missing `package.json` is the only thing left that I use `napa` for from my own `package.json`.

**Comment by lgrignon** [comment]
@gildas-lormeau Could you find a little bit of time to merge this please? It would be great :)

**Comment by lgrignon** [comment]
After 15 months.. seriously? :)

Do what you want with the maintainer field once merged but I doubt there is any maintainer on this project anymore ;)

**Comment by krokofant** [comment]
@lgrignon Sorry :sweat_smile:

**Comment by Rob--W** [comment]
FYI I perform some (minimal) maintenance of this project, by reviewing PRs and looking at some issues.

I think that in the current state, this project is not suitable for the npm registry because:

1. There are no active developers on this project.
2. There is no documentation on how to use zip.js (in a browser environment) after `npm install`.
3. It cannot be used in Node.js, even though the core functionality is independent of DOM (the few references to `document` / `Worker` can easily be replaced with alternatives).

**Comment by krokofant** [comment]
@Rob--W There exists docs on the website on how to use it. Not the clearest but it works.


I think this should be merged because it allows installing _with npm_ directly from github and _it doesn't need to be published on npm repo_.

Adding the simple package.json allows for easier management of the package instead of downloading och cloning a release manually just to use it.

**Comment by lgrignon** [comment]
Thanks @krokofant, that was the spirit indeed.
@Rob--W many people now use npm for front-end development, and there are many front-end only libraries on the npm registry. I think this would be useful to have zip.js as well and nothing is required from the documentation because the usage doesn't change that much.
Thank you again :)

**Comment by hciyang** [comment]
Can this be merged?

**Comment by lgrignon** [comment]
I think the original author has gone to another planet :)

**Comment by krokofant** [comment]
Someone else could just fork it and add the package.json to their own git and install it via npm. Better yet just publish a copy of this on npm.

**Comment by lgrignon** [comment]
Well I can deploy my fork from which I created this PR

**Comment by lgrignon** [comment]
Done:
https://www.npmjs.com/package/@lgrignon/zip.js

**Comment by YonathanB** [comment]
> Done:
> https://www.npmjs.com/package/@lgrignon/zip.js

Doesn't work

**Comment by gildas-lormeau** [comment]
I added a package.json in the project and the library can be now downloaded via jsdeliver. I'll probably publish it on npm soon.

**Comment by PhilippWendler** [comment]
Thanks for your recent work on this project! We are very glad see to see this is revived. A published package on npmjs.com would be the icing on the cake.

**Comment by gildas-lormeau** [comment]
@PhilippWendler Thank you for the kind words! I'll try to publish it very soon then ;)

**Comment by gildas-lormeau** [comment]
@PhilippWendler That's done, the library is on now on NPM, see https://www.npmjs.com/package/@zip.js/zip.js

**Comment by PhilippWendler** [comment]
Wow, that was fast! Thank you very much!

We really like your library because of the possibility to extract individual files from a remote ZIP (via HTTP) without downloading the whole zip, btw.

**Comment by gildas-lormeau** [comment]
@PhilippWendler You're welcome. Thank you for the feedback, I had a similar need when I created zip.js. That's why the library exists actually ;)

**Pull request closed without merging**
