### PR TITLE
Yet another fix for #80

### PR DESCRIPTION
**Pull request by ryanackley**
See #80

### CODE REVIEW

**Comment by Rob--W** [comment]
I like this clean patch.

One concern: In theory, the existing code allows the browser to optimize memory usage by moving putting the data in a file (Blobs do not need to fully exist in memory). Furthermore, after the data has been added to the Blob, all written bytes are owned by the BlobWriter, i.e. if callers modify the typed array, it won't unexpectedly change the content of the BlobWriter.

After the patch, these two features may not hold any more:

1. All data need to fully exist in memory (because they are held in an array). This is a **huge** issue, because it prevents the use of BlobWriters with big files.
2. Changes made to the typed array after writing the typed array will also affect the data held by the BlobWriter.

Could you write a test / demo that shows that the first point is not an issue? E.g. if your demo shows that zip.js presently fails to work with big typed arrays, then applying this patch will not do any damage either. But if zip.js can work fine with, say, files of 2 GB, and after applying your patch zip.js fails to work, then the patch is unacceptable in its present form.

For 2, I do not know from the top of my head whether the API allows us to "take ownership" of any input. It seems unlikely though, but if you can point out that the existing API already fails when the input is modified after write, then I'll accept the patch.

**Comment by ryanackley** [comment]
Hi @Rob--W , this [chrome bug](https://code.google.com/p/chromium/issues/detail?id=375297) is the root cause of #80. It's different than [this one](https://code.google.com/p/chromium/issues/detail?id=224251) which is the one referenced from #80 that really just is an example of what happens after you reach the blob memory limit.

If you go read the bug I linked and follow the comments, you will see that Chrome uses memory exclusively for Blobs and there is a 500MB limit. Every blob seems to count towards this limit, even blobs that share the same data. So for example this statement in the current implementation of zip.js

```javascript
blob = new Blob([ blob, appendABViewSupported ? array : array.buffer ], {
				type : contentType
           });
```
Will add `(blob.size * 2) + array.length` to the memory usage limit. You can verify this yourself by stepping through an unzip operation and going to chrome://blob-internals. You will see a new blob being created and held onto each time the statement is called but at the same time all of the previous blobs in the chain are sticking around

I researched all of this for the readium epub reader project. See [this bug](https://github.com/readium/readium-js-viewer/issues/280). We use zip.js to unzip e-books for viewing. We were unable to extract files as small as 20MB from a zip file. This patch fixes it.

**Comment by Rob--W** [comment]
How does this patch affect the memory usage in other browsers, such as Firefox? And what about the second question in my comment?

**Comment by ryanackley** [comment]
With regard to other browsers, keep in mind we're talking about the memory required to hold the data of a single entry in the zip file. Even chrome books have 1 or 2 gb of memory. I would argue that there is a middle ground. Do you want the ability to unzip a 120 gb entry on FF but not even 20MB entry on Chrome?

For 2, I understand the concern and I think it's valid. For example, someone may decide in the future to re-use the typed arrays for performance reasons or something. The only way to prevent this would be to copy the data but this would increase memory usage and potentially decrease performance. I say cross that bridge when you come to it. It's definitely not a problem right at this moment.

**Comment by Rob--W** [comment]
> With regard to other browsers, keep in mind we're talking about the memory required to hold the data of a single entry in the zip file. Even chrome books have 1 or 2 gb of memory. I would argue that there is a middle ground. Do you want the ability to unzip a 120 gb entry on FF but not even 20MB entry on Chrome?

No, but if the patch significantly degrades the performance in other browsers, then we could add browser sniffing to the code. Could you test the effect of your patch on the memory usage in Firefox? Does this bug exist in Safari, by the way?

> For 2, I understand the concern and I think it's valid. For example, someone may decide in the future to re-use the typed arrays for performance reasons or something. The only way to prevent this would be to copy the data but this would increase memory usage and potentially decrease performance. I say cross that bridge when you come to it. It's definitely not a problem right at this moment.

Then make sure that it is documented. Check out to the gh-pages branch and update the documentation over there to state that the passed-in objects cannot be re-used. And also update the commit message to mention this backwards-incompatible change, in case someone scans commit messages to see whether they should upgrade.

**Comment by ryanackley** [comment]
A potential solution for all concerns would be to just wrap the array in a new blob then store this blob in the `data` array then construct the final Blob when getData is called. 

This avoids the "chaining" (`blob = new Blob([blob, array])`) that is causing the exponential memory growth in Chrome. It allows for Blob optimizations by the browser and also it takes ownership of the data in the array so changes don't get propagated to the underlying Blob.

**Comment by Rob--W** [comment]
@ryanackley Sounds good to me. Could you amend your commit with that change?

By the way, I just looked at the Chrome bug, and it [seems that the bug has been fixed two weeks ago](https://code.google.com/p/chromium/issues/detail?id=375297#c31), so even without the patch, the bug will solve itself after 6 weeks. You can try to confirm this with Chrome Canary.

**Comment by Rob--W** [comment]
https://crbug.com/224251 has been fixed in Chrome 42 (which is the current stable version), which makes this patch obsolete. Thanks for your efforts anyway!

**Pull request closed without merging**
